#!/bin/bash -e

: "${BRANCH_TO_MERGE?}" "${BRANCH_TO_MERGE_INTO?}"
: "${GITHUB_TOKEN?}" "${GITHUB_REPO?}"

repo_temp=$(mktemp -d)
git clone "https://github.com/$GITHUB_REPO" "$repo_temp"

cd "$repo_temp"

git checkout "$BRANCH_TO_MERGE_INTO"

git reset --hard origin/"$BRANCH_TO_MERGE"

push_uri="https://$GITHUB_TOKEN@github.com/$GITHUB_REPO"

git push -f "$push_uri" "$BRANCH_TO_MERGE_INTO" >/dev/null 2>&1

fetch_uri="https://github.com/$GITHUB_REPO"

git fetch "$fetch_uri"

git push "$push_uri" :"$BRANCH_TO_MERGE" >/dev/null 2>&1